name: "clear drupal cache"
on:
  schedule:
  - cron: "*/30 * * * *"
jobs:
  build:
    container:
      image: quay.io/pantheon-public/build-tools-ci:6.x
      options: --user root
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - name: Deployment Processing
      env:
        TERMINUS_MACHINE_TOKEN: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        PANTHEON_SITE: ${{ secrets.PANTHEON_SITE }}
      run: |
        terminus -n auth:login --machine-token=$TERMINUS_MACHINE_TOKEN
        terminus drush $PANTHEON_SITE.cl -- cr